### ISSUE TITLE
Error in get_alfred_series function

### ISSUE THREAD

**Issue by MercerAt251** [onnokleen/alfred#4]
For the series_id = "USEPUINDXD" the function, get_alfred_series, results in the following error: 

Error in alfred::get_alfred_series("USEPUINDXD", "EPU", observation_start = "2007-04-30",  : 
  Download of specified time-series failed - did you misspell the identifier?

I am able to use the same series_id with the get_fred_series function without error.

**Comment by onnokleen** [comment]
I think the request times out because the vintage data is too large.

get_alfred_series("USEPUINDXD", realtime_start = "2020-07-28", realtime_end = "2020-07-28")

does work. However, I saw that there are dplyr incompatibility warnings because of changes in dplyr that I have to address at some point: 

Warnmeldungen:
1: `mutate_()` is deprecated as of dplyr 0.7.0.
Please use `mutate()` instead.
See vignette('programming') for more help
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
2: `filter_()` is deprecated as of dplyr 0.7.0.
Please use `filter()` instead.
See vignette('programming') for more help

**Comment by fmrlz** [comment]
Hi I have a similar problem and the same error occurs even if I run this code without calling library(dplyr). Any idea about how to solve it? Thanks!
> get_alfred_series("INDPRO", "indpro")
Error in get_alfred_series("INDPRO", "indpro") : 
  Download of specified time-series failed - did you misspell the identifier?

**Comment by onnokleen** [comment]
> Hi I have a similar problem and the same error occurs even if I run this code without calling library(dplyr). Any idea about how to solve it? Thanks!
> 
> > get_alfred_series("INDPRO", "indpro")
> > Error in get_alfred_series("INDPRO", "indpro") :
> > Download of specified time-series failed - did you misspell the identifier?

Sorry, I can't replicate this issue.

**Comment by onnokleen** [comment]
Given that there was no feedback in the last month, I will close this issue as I can't replicate it.
